.\" 
.\" Author: Łukasz Buśko
.\" Contact: http://str0g.wordpress.com
.\" Copyright: 2010-211
.\"
.TH LittleBenchmark:HDD 1 "September 15, 2010" Linux "User Manuals"
.SH NAME
LittleBenchmark:HDD \- Real life benchmark for for any hard drive which support read/write.
.SH SYNOPSIS
.B LittleBenchmark:HDD [
.I args
.B ] [
.I parm
.B ]
.SH DESCRIPTION
.B LittleBenchmark:HDD 
Test real life driver performance because does not override any system caching capabilities.
Reason to do so is to check if component which you would like to buy/bought made any performance differences.
.\" .BR next benchmark... (1)
.SH OPTIONS
.IP -h
Print usage information and quit
.SH FILES
.I ~/.littlebenchmark/hdd/.config.cfg
.RS
User configuration file.
.SH ENVIRONMENT
.IP "Memory licking"
.RS 
Please read
.B ReadMe.pdf

.\" .SH DIAGNOSTICS

.SH BUGS
Please read
.B ReadMe.pdf
.SH AUTHOR
Łukasz Buśko <buskol.waw.pl@gmail.com>
.SH "SEE ALSO"
.\".BR next bench (1),
